name: reqbotui
description: "A new Flutter project."

# Prevent accidental publishing
publish_to: 'none'

# Versioning
version: 1.0.0+1

# SDK Compatibility
environment:
  sdk: ">=2.12.0 <4.0.0" # Updated to be compatible with Flutter's latest versions

# Dependencies
dependencies:
  flutter:
    sdk: flutter
  file_picker: ^8.1.4   # File picker for handling file uploads
  cupertino_icons: ^1.0.8 # For iOS-style icons

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0 # Linting for better code practices

# Flutter-specific Configuration
flutter:
  uses-material-design: true

  # Assets Configuration
  assets:
    - assets/images/bye.jfif
